variable "ssh_private_key" {
  type = string
  description = "The ssh private key that will be used to allow the opc user to ssh to the compute instance"
}

variable "host_ips" {
  type = list(any)
  description = "The list of ip addresses that will be connected using opc user"
}

variable "num_vm_instances" {
  type        = string
  description = "The number of compute instances that are available"
}

variable "mode" {
  type        = string
  description = "Select mode for development(DEV) or production(PROD). In development mode, local VM scripts zip is seeded on WLS VMs "
}

variable "bastion_host" {
  type        = string
  description = "The bastion ip address that will be used to connect to compute instance using opc user"
  default = ""
}

variable "bastion_host_private_key" {
  type = string
  description = "The ssh private key that will be used to allow the opc user to ssh to the bastion instance"
  default = ""
}

variable "assign_public_ip" {
  type    = bool
  description = "A public IP address to an instance to enable communication with the internet"
  default = true
}

variable "is_bastion_instance_required" {
  type    = bool
  description = "Whether bastion instance is required to connect to the compute instance"
  default = true
}

variable "existing_bastion_instance_id" {
  type = string
  description = "An Ocid of the existing bastion instance to connect to the compute instance"
}

variable "wlsoci_vmscripts_zip_bundle" {
  type = string
  description = "wlsoci vmscripts zip bundle that is generated by the build"
}